--------------------------------------------------------
--  File created - Monday-March-21-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------
CREATE TABLE "ADMIN" (
  "FELHASZNALONEV" VARCHAR2(40 BYTE),
  "INTEZET" VARCHAR2(60 BYTE),
  "TUDOMANYOS_FOKOZAT" VARCHAR2(40 BYTE),
  "SZAKTERULET" VARCHAR2(40 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table CIKK
--------------------------------------------------------
CREATE TABLE "CIKK" (
  "CIM" VARCHAR2(40 BYTE),
  "TARTALOM" VARCHAR2(300 BYTE),
  "LETREHOZAS_DATUM" DATE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table FELHASZNALO
--------------------------------------------------------
CREATE TABLE "FELHASZNALO" (
  "FELHASZNALONEV" VARCHAR2(40 BYTE),
  "SZERZO_E" CHAR(1 BYTE),
  "EMAIL" VARCHAR2(40 BYTE),
  "JELSZO" VARCHAR2(40 BYTE),
  "SZUL_DATUM" DATE
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table FORRAS
--------------------------------------------------------
CREATE TABLE "FORRAS" (
  "CIM" VARCHAR2(40 BYTE),
  "HIVATKOZAS" VARCHAR2(30 BYTE),
  "TARTALOM" VARCHAR2(200 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table HIBA_BEJELENTES
--------------------------------------------------------
CREATE TABLE "HIBA_BEJELENTES" (
  "CIM" VARCHAR2(40 BYTE),
  "HIBAJELENTES" VARCHAR2(100 BYTE),
  "HIBANEV" VARCHAR2(20 BYTE),
  "FELHASZNALONEV" VARCHAR2(40 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table KULCSSZO
--------------------------------------------------------
CREATE TABLE "KULCSSZO" (
  "CIM" VARCHAR2(40 BYTE),
  "MEGNEVEZES" VARCHAR2(30 BYTE),
  "LINK" VARCHAR2(30 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table MODOSITAS
--------------------------------------------------------
CREATE TABLE "MODOSITAS" (
  "CIM" VARCHAR2(40 BYTE),
  "MIKOR" DATE,
  "FELHASZNALONEV" VARCHAR2(40 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Table TEMAKOR
--------------------------------------------------------
CREATE TABLE "TEMAKOR" (
  "CIM" VARCHAR2(40 BYTE),
  "NEV" VARCHAR2(30 BYTE),
  "ALTEMAKOR" VARCHAR2(30 BYTE),
  "TARTALOM" VARCHAR2(200 BYTE)
) SEGMENT CREATION IMMEDIATE PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

REM INSERTING into GYURI.ADMIN
SET
  DEFINE OFF;

REM INSERTING into GYURI.CIKK
SET
  DEFINE OFF;

REM INSERTING into GYURI.FELHASZNALO
SET
  DEFINE OFF;

REM INSERTING into GYURI.FORRAS
SET
  DEFINE OFF;

REM INSERTING into GYURI.HIBA_BEJELENTES
SET
  DEFINE OFF;

REM INSERTING into GYURI.KULCSSZO
SET
  DEFINE OFF;

REM INSERTING into GYURI.MODOSITAS
SET
  DEFINE OFF;

REM INSERTING into GYURI.TEMAKOR
SET
  DEFINE OFF;

--------------------------------------------------------
--  DDL for Index ADMIN_PK
--------------------------------------------------------
CREATE UNIQUE INDEX "ADMIN_PK" ON "ADMIN" ("FELHASZNALONEV") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Index CIKK_PK
--------------------------------------------------------
CREATE UNIQUE INDEX "CIKK_PK" ON "CIKK" ("CIM") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Index FELHASZNALO_PK
--------------------------------------------------------
CREATE UNIQUE INDEX "FELHASZNALO_PK" ON "FELHASZNALO" ("FELHASZNALONEV") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Index FORRAS_PK
--------------------------------------------------------
CREATE UNIQUE INDEX "FORRAS_PK" ON "FORRAS" ("CIM", "HIVATKOZAS") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Index HIBA_BEJELENTES_PK
--------------------------------------------------------
CREATE UNIQUE INDEX "HIBA_BEJELENTES_PK" ON "HIBA_BEJELENTES" ("FELHASZNALONEV", "CIM") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Index KULCSSZO_PK
--------------------------------------------------------
CREATE UNIQUE INDEX "KULCSSZO_PK" ON "KULCSSZO" ("CIM", "MEGNEVEZES") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Index MODOSITAS_PK
--------------------------------------------------------
CREATE UNIQUE INDEX "MODOSITAS_PK" ON "MODOSITAS" ("CIM", "FELHASZNALONEV") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  DDL for Index TEMAKOR_PK
--------------------------------------------------------
CREATE UNIQUE INDEX "TEMAKOR_PK" ON "TEMAKOR" ("CIM", "NEV") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
  INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
) TABLESPACE "USERS";

--------------------------------------------------------
--  Constraints for Table FELHASZNALO
--------------------------------------------------------
ALTER TABLE
  "FELHASZNALO"
ADD
  CONSTRAINT "FELHASZNALO_PK" PRIMARY KEY ("FELHASZNALONEV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;

ALTER TABLE
  "FELHASZNALO"
MODIFY
  ("SZUL_DATUM" NOT NULL ENABLE);

ALTER TABLE
  "FELHASZNALO"
MODIFY
  ("JELSZO" NOT NULL ENABLE);

ALTER TABLE
  "FELHASZNALO"
MODIFY
  ("EMAIL" NOT NULL ENABLE);

ALTER TABLE
  "FELHASZNALO"
MODIFY
  ("SZERZO_E" NOT NULL ENABLE);

ALTER TABLE
  "FELHASZNALO"
MODIFY
  ("FELHASZNALONEV" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table CIKK
--------------------------------------------------------
ALTER TABLE
  "CIKK"
ADD
  CONSTRAINT "CIKK_PK" PRIMARY KEY ("CIM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;

ALTER TABLE
  "CIKK"
MODIFY
  ("LETREHOZAS_DATUM" NOT NULL ENABLE);

ALTER TABLE
  "CIKK"
MODIFY
  ("TARTALOM" NOT NULL ENABLE);

ALTER TABLE
  "CIKK"
MODIFY
  ("CIM" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table MODOSITAS
--------------------------------------------------------
ALTER TABLE
  "MODOSITAS"
ADD
  CONSTRAINT "MODOSITAS_PK" PRIMARY KEY ("CIM", "FELHASZNALONEV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;

ALTER TABLE
  "MODOSITAS"
MODIFY
  ("FELHASZNALONEV" NOT NULL ENABLE);

ALTER TABLE
  "MODOSITAS"
MODIFY
  ("MIKOR" NOT NULL ENABLE);

ALTER TABLE
  "MODOSITAS"
MODIFY
  ("CIM" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------
ALTER TABLE
  "ADMIN"
ADD
  CONSTRAINT "ADMIN_PK" PRIMARY KEY ("FELHASZNALONEV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;

ALTER TABLE
  "ADMIN"
MODIFY
  ("SZAKTERULET" NOT NULL ENABLE);

ALTER TABLE
  "ADMIN"
MODIFY
  ("TUDOMANYOS_FOKOZAT" NOT NULL ENABLE);

ALTER TABLE
  "ADMIN"
MODIFY
  ("INTEZET" NOT NULL ENABLE);

ALTER TABLE
  "ADMIN"
MODIFY
  ("FELHASZNALONEV" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table KULCSSZO
--------------------------------------------------------
ALTER TABLE
  "KULCSSZO"
ADD
  CONSTRAINT "KULCSSZO_PK" PRIMARY KEY ("CIM", "MEGNEVEZES") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;

ALTER TABLE
  "KULCSSZO"
MODIFY
  ("LINK" NOT NULL ENABLE);

ALTER TABLE
  "KULCSSZO"
MODIFY
  ("MEGNEVEZES" NOT NULL ENABLE);

ALTER TABLE
  "KULCSSZO"
MODIFY
  ("CIM" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table TEMAKOR
--------------------------------------------------------
ALTER TABLE
  "TEMAKOR"
ADD
  CONSTRAINT "TEMAKOR_PK" PRIMARY KEY ("CIM", "NEV") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;

ALTER TABLE
  "TEMAKOR"
MODIFY
  ("TARTALOM" NOT NULL ENABLE);

ALTER TABLE
  "TEMAKOR"
MODIFY
  ("ALTEMAKOR" NOT NULL ENABLE);

ALTER TABLE
  "TEMAKOR"
MODIFY
  ("NEV" NOT NULL ENABLE);

ALTER TABLE
  "TEMAKOR"
MODIFY
  ("CIM" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table HIBA_BEJELENTES
--------------------------------------------------------
ALTER TABLE
  "HIBA_BEJELENTES"
ADD
  CONSTRAINT "HIBA_BEJELENTES_PK" PRIMARY KEY ("FELHASZNALONEV", "CIM") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;

ALTER TABLE
  "HIBA_BEJELENTES"
MODIFY
  ("FELHASZNALONEV" NOT NULL ENABLE);

ALTER TABLE
  "HIBA_BEJELENTES"
MODIFY
  ("HIBANEV" NOT NULL ENABLE);

ALTER TABLE
  "HIBA_BEJELENTES"
MODIFY
  ("HIBAJELENTES" NOT NULL ENABLE);

ALTER TABLE
  "HIBA_BEJELENTES"
MODIFY
  ("CIM" NOT NULL ENABLE);

--------------------------------------------------------
--  Constraints for Table FORRAS
--------------------------------------------------------
ALTER TABLE
  "FORRAS"
ADD
  CONSTRAINT "FORRAS_PK" PRIMARY KEY ("CIM", "HIVATKOZAS") USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE(
    INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  ) TABLESPACE "USERS" ENABLE;

ALTER TABLE
  "FORRAS"
MODIFY
  ("TARTALOM" NOT NULL ENABLE);

ALTER TABLE
  "FORRAS"
MODIFY
  ("HIVATKOZAS" NOT NULL ENABLE);

ALTER TABLE
  "FORRAS"
MODIFY
  ("CIM" NOT NULL ENABLE);

--------------------------------------------------------
--  Ref Constraints for Table ADMIN
--------------------------------------------------------
ALTER TABLE
  "ADMIN"
ADD
  CONSTRAINT "ADMIN_FK1" FOREIGN KEY ("FELHASZNALONEV") REFERENCES "FELHASZNALO" ("FELHASZNALONEV") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table FORRAS
--------------------------------------------------------
ALTER TABLE
  "FORRAS"
ADD
  CONSTRAINT "FORRAS_FK1" FOREIGN KEY ("CIM") REFERENCES "CIKK" ("CIM") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table HIBA_BEJELENTES
--------------------------------------------------------
ALTER TABLE
  "HIBA_BEJELENTES"
ADD
  CONSTRAINT "HIBA_BEJELENTES_FK1" FOREIGN KEY ("CIM") REFERENCES "CIKK" ("CIM") ENABLE;

ALTER TABLE
  "HIBA_BEJELENTES"
ADD
  CONSTRAINT "HIBA_BEJELENTES_FK2" FOREIGN KEY ("FELHASZNALONEV") REFERENCES "FELHASZNALO" ("FELHASZNALONEV") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table KULCSSZO
--------------------------------------------------------
ALTER TABLE
  "KULCSSZO"
ADD
  CONSTRAINT "KULCSSZO_FK1" FOREIGN KEY ("CIM") REFERENCES "CIKK" ("CIM") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table MODOSITAS
--------------------------------------------------------
ALTER TABLE
  "MODOSITAS"
ADD
  CONSTRAINT "MODOSITAS_FK1" FOREIGN KEY ("CIM") REFERENCES "CIKK" ("CIM") ENABLE;

ALTER TABLE
  "MODOSITAS"
ADD
  CONSTRAINT "MODOSITAS_FK2" FOREIGN KEY ("FELHASZNALONEV") REFERENCES "FELHASZNALO" ("FELHASZNALONEV") ENABLE;

--------------------------------------------------------
--  Ref Constraints for Table TEMAKOR
--------------------------------------------------------
ALTER TABLE
  "TEMAKOR"
ADD
  CONSTRAINT "TEMAKOR_FK1" FOREIGN KEY ("CIM") REFERENCES "CIKK" ("CIM") ENABLE;